#!/usr/bin/env zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap 

yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   08

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Secondary"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Comms"
yabai -m space 5 --label "Media"
yabai -m space 6 --label "Float"

# Space config
yabai -m config --space 6 layout Float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off

# Primary
yabai -m rule --add app="kitty"                 space=1

# Secondary
yabai -m rule --add app="Google Chrome"         space=2

# Tools
yabai -m rule --add app="Finder"                space=3
yabai -m rule --add app="Notion"                space=3
yabai -m rule --add app="Postman"               space=3
yabai -m rule --add app="Activity Monitor"      space=3
yabai -m rule --add app="Terminal"              space=3

# Communication
yabai -m rule --add app="Slack"                 space=4
yabai -m rule --add app="Mail"                  space=4
yabai -m rule --add app="Calendar"              space=4

# Media
yabai -m rule --add app="Music"                 space=5
yabai -m rule --add app="QuickTime Player"      space=5
yabai -m rule --add app="VLC"                   space=5
yabai -m rule --add app="Spotify"               space=5

# Floating
yabai -m rule --add app="^System Preferences$"  space=6

# yabai -m config external_bar main:20:0

echo "yabai configuration loaded.."
