-- return {
--   'AckslD/nvim-whichkey-setup.lua',
--   requires = { 'liuchengxu/vim-which-key' },
--   config = function()
--     local wk = require('whichkey_setup')
--     wk.config({
--       default_keymap_settings = {
--         silent = true,
--         noremap = true,
--       },
--       default_mode = 'n'
--     })
--
--     local keymap = {
--       x = 'quit buffer',
--       X = 'force quit buffer',
--       s = 'save',
--       o = 'find files',
--       f = {
--         f = 'find files',
--         g = 'grep search',
--         b = 'buffer search',
--         h = 'find help refs',
--       },
--       n = 'toggle tree',
--       r = 'refresh tree',
--   --    / = 'comment',
--    --   ? = 'block comment',
--       f = 'search buffer 2 chars',
--       F = 'search buffer before cursor 2 chars',
--       w = 'search buffer word',
--       W = 'search buffer word BC',
--       l = 'search buffer line'
--     }
--
--    wk.register_keymap('leader', keymap)
--   end
-- }
